[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --workspaces --include-workspace-root"]

[phases.build]
cmds = ["npm run build:admin"]

[start]
cmd = "npm run start --workspace=@catedral/admin"
