[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install --workspaces --include-workspace-root"]

[phases.build]
cmds = [
  "npx prisma generate --schema=apps/api/prisma/schema.prisma",
  "npm run build:api"
]

[phases.deploy]
cmds = ["npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma"]

[start]
cmd = "npm run start:api"
